const steamPlayers = [
  { nick: "Player1", level: 42, vacBan: false },
  { nick: "Player2", level: 17, vacBan: false },
  { nick: "Player3", level: 89, vacBan: false },
  { nick: "Player4", level: 23, vacBan: false },
  { nick: "Player5", level: 61, vacBan: false },
  { nick: "Player6", level: 35, vacBan: false },
  { nick: "Player7", level: 77, vacBan: false },
  { nick: "Player8", level: 50, vacBan: false },
  { nick: "Player9", level: 5, vacBan: false },
  { nick: "Player10", level: 96, vacBan: true },  // VAC ban
  { nick: "Player11", level: 11, vacBan: false },
  { nick: "Player12", level: 68, vacBan: false },
  { nick: "Player13", level: 29, vacBan: false },
  { nick: "Player14", level: 81, vacBan: false },
  { nick: "Player15", level: 32, vacBan: false },
  { nick: "Player16", level: 44, vacBan: false },
  { nick: "Player17", level: 73, vacBan: false },
  { nick: "Player18", level: 16, vacBan: false },
  { nick: "Player19", level: 54, vacBan: false },
  { nick: "Player20", level: 99, vacBan: false },
  { nick: "Player21", level: 63, vacBan: false },
  { nick: "Player22", level: 25, vacBan: false },
  { nick: "Player23", level: 8, vacBan: false },
  { nick: "Player24", level: 40, vacBan: false },
  { nick: "Player25", level: 71, vacBan: false },
  { nick: "Player26", level: 14, vacBan: false },
  { nick: "Player27", level: 56, vacBan: false },
  { nick: "Player28", level: 21, vacBan: false },
  { nick: "Player29", level: 38, vacBan: false },
  { nick: "Player30", level: 84, vacBan: false },
  { nick: "Player31", level: 3, vacBan: false },
  { nick: "Player32", level: 46, vacBan: false },
  { nick: "Player33", level: 66, vacBan: false },
  { nick: "Player34", level: 12, vacBan: false },
  { nick: "Player35", level: 27, vacBan: false },
  { nick: "Player36", level: 74, vacBan: false },
  { nick: "Player37", level: 19, vacBan: false },
  { nick: "Player38", level: 36, vacBan: false },
  { nick: "Player39", level: 59, vacBan: false },
  { nick: "Player40", level: 92, vacBan: false },
  { nick: "Player41", level: 7, vacBan: false },
  { nick: "Player42", level: 30, vacBan: false },
  { nick: "Player43", level: 65, vacBan: true },  // VAC ban
  { nick: "Player44", level: 15, vacBan: false },
  { nick: "Player45", level: 48, vacBan: false },
  { nick: "Player46", level: 82, vacBan: false },
  { nick: "Player47", level: 2, vacBan: false },
  { nick: "Player48", level: 70, vacBan: false },
  { nick: "Player49", level: 22, vacBan: false },
  { nick: "Player50", level: 90, vacBan: true }   // VAC ban
];
