const steamPlayers = [
  { nick: "ShadowReaper", level: 42, vacBan: false },
  { nick: "NoScopeKing", level: 17, vacBan: false },
  { nick: "xXDragonSlayerXx", level: 89, vacBan: false },
  { nick: "ToxicAvenger", level: 23, vacBan: false },
  { nick: "PixelGhost", level: 61, vacBan: false },
  { nick: "HeadshotMachine", level: 35, vacBan: false },
  { nick: "CyberWolf", level: 77, vacBan: false },
  { nick: "EZClap", level: 50, vacBan: false },
  { nick: "SilentNinja", level: 5, vacBan: false },
  { nick: "RageQuitter", level: 96, vacBan: true },   // VAC ban
  { nick: "M0nsterKill", level: 11, vacBan: false },
  { nick: "DarkLord", level: 68, vacBan: false },
  { nick: "Sn1perElite", level: 29, vacBan: false },
  { nick: "TwitchyFingers", level: 81, vacBan: false },
  { nick: "LagSwitch", level: 32, vacBan: false },
  { nick: "NeoSamurai", level: 44, vacBan: false },
  { nick: "RocketBoi", level: 73, vacBan: false },
  { nick: "AFKMaster", level: 16, vacBan: false },
  { nick: "BloodHunter", level: 54, vacBan: false },
  { nick: "ClutchOrKick", level: 99, vacBan: false },
  { nick: "Cyb3rCat", level: 63, vacBan: false },
  { nick: "PotatoAimer", level: 25, vacBan: false },
  { nick: "OneTapOnly", level: 8, vacBan: false },
  { nick: "TryHarder", level: 40, vacBan: false },
  { nick: "Ping200", level: 71, vacBan: false },
  { nick: "PixelWarrior", level: 14, vacBan: false },
  { nick: "SweatyPalms", level: 56, vacBan: false },
  { nick: "Cr4zyFrog", level: 21, vacBan: false },
  { nick: "SmurfLord", level: 38, vacBan: false },
  { nick: "EZFrag", level: 84, vacBan: false },
  { nick: "RustyKnife", level: 3, vacBan: false },
  { nick: "BombHasBeenPlanted", level: 46, vacBan: false },
  { nick: "No0bMaster69", level: 66, vacBan: false },
  { nick: "CampingCarl", level: 12, vacBan: false },
  { nick: "RushB", level: 27, vacBan: false },
  { nick: "QuickScopePro", level: 74, vacBan: false },
  { nick: "DerankMe", level: 19, vacBan: false },
  { nick: "SilentButDeadly", level: 36, vacBan: false },
  { nick: "TrollFace", level: 59, vacBan: false },
  { nick: "VacBannedSoon", level: 92, vacBan: false },
  { nick: "ClownFiesta", level: 7, vacBan: false },
  { nick: "PixelatedSoul", level: 30, vacBan: false },
  { nick: "WallHackSus", level: 65, vacBan: true },   // VAC ban
  { nick: "ShadowStep", level: 15, vacBan: false },
  { nick: "BananaShot", level: 48, vacBan: false },
  { nick: "TTV_Streamer", level: 82, vacBan: false },
  { nick: "KnifeCollector", level: 2, vacBan: false },
  { nick: "ToxicSmile", level: 70, vacBan: false },
  { nick: "Dust2Only", level: 22, vacBan: false },
  { nick: "VACationTime", level: 90, vacBan: true }   // VAC ban
];
